apiVersion: v1
kind: Service
metadata:
    name: svc-wordpress
    labels:
        app: wordpress
spec:
    type: LoadBalancer
    ports: 
    - port: 80
    selector:
        app: wordpress
        tier: frontend


