apiVersion: apps/v1
kind: Deployment
metadata:
  name: de-redis
spec:
  replicas: 5
  selector:
    matchLabels:
      type: middle-tier
  template:
    metadata:
      name: redis
      labels:
        type: middle-tier
    spec:
      containers:
        - name: redis
          image: redis
