apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota-dev
  namespace: mural-dev
spec:
  hard:
    pods: "4"
    requests.cpu: "4"
    requests.memory: 5Gi
    limits.cpu: "10"
    limits.memory: 10Gi
