apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy: {}
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        type: redis
      volumes:
      - name: data
        emptyDir:
          path: /redis-master-data
      containers:
      - image: redis:alpine
        name: redis
        volumeMounts:
        - mountPath: /data
          name: data
        resources: 
          requests:
            cpu: .2
          limits:
            cpu: .4
      
status: {}
