apiVersion: v1
kind: Pod
metadata:
  labels:
    run: time-check
  name: time-check
spec:
  containers:
  - image: busybox
    name: time-check
    resources: {}
    command: ["/bin/sh"]
    args: ["-c", "while true; do date >> /data/out.log; sleep $(wait_time);echo waiting for $(wait_time) seconds; done;"]
    volumeMounts:
    - name: data
      mountPath: /data
    env:
    - name: wait_time
      valueFrom:
        configMapKeyRef:
          name: time-config
          key: TIME_FREQ
  volumes:
  - name: data
    hostPath:
      path: /var/local/aaa
      type: DirectoryOrCreate
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
