apiVersion: v1
kind: Pod
metadata:
    name: random-number-generator
spec:
    containers:
    - image: alpine
      name: alpine
      command: ["/bin/sh", "-c"]
      args: ["shuf -i 0-100 -n 1 /opt/numberout.out;"]
      volumeMounts:
      - mountPath: /work
        name: data-volume

    volumes:
    - name: data-volume
      hostpath:
        path: /work
        type: Directory