apiVersion: v1
kind: ReplicationController
metadata: 
  name: wordpress
  labels:
     name: wordpress-rc
     type: web-server
spec:
  template:
    metadata:
      labels:      
        app: wordpress-pod
        type: web-server
    spec:
      containers:
        - name: wordpress
          image: wordpress
  replicas: 3          
