apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: wordpress
  labels:
     name: wordpress-rc
     type: web-server
spec:
  template:
    metadata:
      labels:      
        app: wordpress-pod
        type: web-server
    spec:
      containers:
        - name: wordpress
          image: wordpress
  replicas: 6 
  selector:
    matchLabels:
      type: web-server  
