apiVersion: v1
kind: Pod
metadata:
    name: nginx
    labels:
        app: webserver

spec:
    containers:
    - image: nginx:alpine
      name: nginx
      ports:
      - containerPort: 80
        protocol: TCP
        
