apiVersion: v1
kind: Pod
metadata:
    name: git-example
    namespace: fortune
    labels:
        app: git-example
spec:
    containers:
    - image: nginx:alpine
      name: web-server
      volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
        readOnly: true
      ports:
      - containerPort: 80
        protocol: TCP
    - image: ustcmirror/gitsync
      name: git-sync
      volumeMounts:
      - name: html
        mountPath: /var/htdocs
    volumes:
    - name: html
      gitRepo:
        repository: https://github.com/venkig-2244/kubia-website-example.git
        revision: master
        directory: .
