apiVersion: v1
kind: Pod
metadata:
    name: mongodb
    namespace: fortune
    labels:
        app: mongodb
        type: backend
spec:
    volumes:
    - name: mongodb-data
      persistentVolumeClaim:
        claimName: mongodb-pvc

    containers:
    - image: mongo
      name: mongodb
      volumeMounts:
      - name: mongodb-data
        mountPath: /data/db
      ports:
      - containerPort: 27017
        protocol: TCP