apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongodb-pvc 
    namespace: fortune
spec:
    resources:
        requests:
            storage: 1Gi
    accessModes: 
    - ReadWriteMany
    storageClassName: ""

