apiVersion: v1
kind: PersistentVolume
metadata:
    name: mongodb-pv 
    namespace: fortune
spec:
    capacity: 
        storage: 1Gi
    accessModes:
    - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    gcePersistentDisk:
      pdName: mongodbpv
      fsType: ext4

