apiVersion: v1
kind: ReplicationController
metadata:
    name: mysql-rc 
    labels:
        app: mysql 
        type: db
spec:
    template:
        metadata:
            name: mysql-pod
            labels: 
                app: mysql
                type: db
        spec:
            containers:
            - name: mysql
              image: mysql:5.6
              env:
                - name: MYSQL_ROOT_PASSWORD
                  value: password
              ports:
                - containerPort: 3306
                  name: mysql
    replicas: 3

