apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: redis-svc
  name: redis-svc
spec:
  ports:
  - port: 8765
    protocol: TCP
    targetPort: 8080
  selector:
    run: redis
status:
  loadBalancer: {}
