apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: sc-fast-pvc1 
spec:
    resources:
        requests:
            storage: 1Gi
    accessModes: 
    - ReadWriteOnce
    storageClassName: fast