apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: ucjob
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: ucjob
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: ubuntu
            name: ucjob
            command: ["/bin/sh"]
            args: ["-c", "echo hello world"]
            resources: {}
          restartPolicy: OnFailure
  schedule: "*/1 * * * *"
status: {}
