apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv007
spec:
    capacity:
        storage: 10Gi
    accessModes:
    - ReadWriteOnce
    storageClassName: normal
    hostPath:
        path: /etc/foo
    