apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvc005
spec:
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 4Gi
    storageClassName: normal
