apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: ckad
spec:
  type: LoadBalancer
  ports: 
    - targetPort: 80
      port: 80
      nodePort: 31000
  selector:
    app: jenkins