apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mysql-claim 
    namespace: wordpress
spec:
    accessModes:
       - ReadWriteOnce
    resources:
        requests:
            storage: 200Gi