apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: ckad
spec:
  type: LoadBalancer
  ports: 
    - targetPort: 8080
      port: 80
      nodePort: 31002
  selector:
    app: jenkins