apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: db
    
spec:
  containers:
    - image: mysql:5.6
      name: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
      ports:
        - containerPort: 3306
          name: mysql
      volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumes:
  - name: mysql-data
    hostPath: 
      path: /usr/data
      type: DirectoryOrCreate
  nodeName: k8s-node3

