apiVersion: batch/v1
kind: Job
metadata:
    name: random-error
spec:
    completions: 3
    parallelism: 3

    template:
        metadata:
            name: random-error
        spec:
          containers:
          - name: random-error
            image: kodekloud/random-error
          restartPolicy: Never

